services:
  tor:
    image: r0shii/tor:dev
    pull_policy: always
    build:
      pull: true
      context: tor
    container_name: tor
    networks:
      private:
        ipv4_address: 10.3.1.2
    volumes:
      - tor:/var/lib/tor
    restart: unless-stopped

  bitcoin:
    image: r0shii/bitcoin:dev
    pull_policy: always
    build:
      pull: true
      args:
        bitcoin_version_tag: v23.0
      context: bitcoin
    container_name: bitcoin
    depends_on:
      - tor
    networks:
      private:
        ipv4_address: 10.3.1.3
    volumes:
        - bitcoin:/var/lib/bitcoin
        - tor:/var/lib/tor:ro
        - ${BITCOIN_BLOCKS_MOUNTPOINT:-.data/bitcoin/.blocks}:/blocks
        - ${BITCOIN_DATA_MOUNTPOINT:-.data/bitcoin}:/home/bitcoin/.bitcoin
    restart: unless-stopped

  joinmarket:
    image: r0shii/joinmarket:dev
    pull_policy: always
    build:
      pull: true
      args:
        joinmarket_version_tag: v0.9.8
      context: joinmarket
    container_name: joinmarket
    depends_on:
      bitcoin:
        condition: service_healthy
    networks:
      - private
    volumes:
      - bitcoin:/var/lib/bitcoin:ro
      - tor:/var/lib/tor:ro
      - ${JOINMARKET_DATA_MOUNTPOINT:-.data/joinmarket}:/srv

  lnd:
    image: r0shii/lnd:dev
    pull_policy: always
    build:
      pull: true
      args:
        lnd_version_tag: v0.15.1-beta
        lit_version_tag: v0.8.0-alpha
      context: lnd
    container_name: lnd
    depends_on:
      bitcoin:
        condition: service_healthy
    networks:
      - private
    volumes:
      - bitcoin:/var/lib/bitcoin:ro
      - tor:/var/lib/tor:ro
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/lnd/.lnd
    ports:
      - "8443:8443"
  lndconnect:
    image: r0shii/lndconnect:dev
    pull_policy: always
    build:
      pull: true
      args:
        version: latest
      context: lndconnect
    container_name: lndconnect
    depends_on:
      lnd:
        condition: service_healthy
    networks:
      - private
    volumes:
      - tor:/var/lib/tor:ro
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/lndconnect/.lnd:rw
  pool:
    image: r0shii/pool:dev
    pull_policy: always
    build:
      pull: true
      args:
        VERSION_TAG: v0.5.8-alpha
      context: pool
    container_name: pool
    depends_on:
      lnd:
        condition: service_healthy
    networks:
      - private
    volumes:
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/pool/.lnd:ro
      - ${POOL_DATA_MOUNTPOINT:-.data/pool}:/home/pool/.pool
  loop:
    image: r0shii/loop:dev
    pull_policy: always
    build:
      pull: true
      args:
        VERSION_TAG: v0.20.1-beta
      context: loop
    container_name: loop
    depends_on:
      lnd:
        condition: service_healthy
    networks:
      - private
    volumes:
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/loop/.lnd:ro
      - ${LOOP_DATA_MOUNTPOINT:-.data/loop}:/home/loop/.loop
  lit:
    image: r0shii/lit:dev
    pull_policy: always
    build:
      pull: true
      args:
        version: v0.8.0-alpha
      context: lit
    container_name: lit
    depends_on:
      lnd:
        condition: service_healthy
    networks:
      - private
    volumes:
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/lit/.lnd:ro
      - ${LIT_DATA_MOUNTPOINT:-.data/lit}:/home/lit/.lit


networks:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.1.0/24

volumes:
  tor:
  bitcoin:
