services:
  tor:
    image: r0shii/tor:dev
    init: true
    pull_policy: always
    build:
      pull: true
      context: tor
    configs:
      - source: torrc
        target: /etc/tor/torrc
    container_name: tor
    networks:
      private:
        ipv4_address: 10.3.1.2
    volumes:
      - tor:/var/lib/tor
    restart: unless-stopped

  bitcoin:
    image: r0shii/bitcoin:dev
    init: true
    pull_policy: always
    build:
      pull: true
      args:
        VERSION_TAG: v23.0
      context: bitcoin
    configs:
      - source: bitcoin
        target: /home/satoshi/.bitcoin/bitcoin.conf
    container_name: bitcoin
    depends_on:
      - tor
    networks:
      private:
        ipv4_address: 10.3.1.3
    volumes:
        - bitcoin:/var/lib/bitcoin
        - tor:/var/lib/tor:ro
        - ${BITCOIN_BLOCKS_MOUNTPOINT:-.data/bitcoin/.blocks}:/blocks
        - ${BITCOIN_DATA_MOUNTPOINT:-.data/bitcoin}:/home/satoshi/.bitcoin
    restart: unless-stopped

  joinmarket:
    image: r0shii/joinmarket:dev
    init: true
    pull_policy: always
    build:
      pull: true
      args:
        VERSION_TAG: v0.9.8
      context: joinmarket
    configs:
      - source: jm
        target: /srv/joinmarket.cfg
    container_name: joinmarket
    depends_on:
      bitcoin:
        condition: service_healthy
    profiles:
      - do-not-start
    networks:
      - private
    volumes:
      - bitcoin:/var/lib/bitcoin:ro
      - tor:/var/lib/tor:ro
      - ${JOINMARKET_DATA_MOUNTPOINT:-.data/joinmarket}:/srv

  lnd:
    image: r0shii/lnd:dev
    init: true
    pull_policy: always
    build:
      pull: true
      args:
        VERSION_TAG: v0.15.1-beta
      context: lnd
    container_name: lnd
    configs:
      - source: bitcoin
        target: /home/satoshi/.lnd/lnd.conf
    depends_on:
      bitcoin:
        condition: service_healthy
    networks:
      - private
    volumes:
      - bitcoin:/var/lib/bitcoin:ro
      - tor:/var/lib/tor:ro
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/satoshi/.lnd
  lndconnect:
    image: r0shii/lndconnect:dev
    init: true
    pull_policy: always
    build:
      pull: true
      args:
        version: latest
      context: lndconnect
    container_name: lndconnect
    depends_on:
      lnd:
        condition: service_healthy
    networks:
      - private
    volumes:
      - tor:/var/lib/tor:ro
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/lndconnect/.lnd:rw
  pool:
    image: r0shii/pool:dev
    init: true
    pull_policy: always
    build:
      pull: true
      args:
        SERVICE: pool
        VERSION_TAG: v0.5.8-alpha
      context: lnlabs
      dockerfile: deamon.Dockerfile
    container_name: pool
    depends_on:
      lnd:
        condition: service_healthy
    networks:
      - private
    volumes:
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/pool/.lnd:ro
      - ${POOL_DATA_MOUNTPOINT:-.data/pool}:/home/pool/.pool
  loop:
    image: r0shii/loop:dev
    init: true
    pull_policy: always
    build:
      pull: true
      args:
        SERVICE: loop
        VERSION_TAG: v0.20.1-beta
      context: lnlabs
      dockerfile: deamon.Dockerfile
    container_name: loop
    depends_on:
      lnd:
        condition: service_healthy
    networks:
      - private
    volumes:
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/loop/.lnd:ro
      - ${LOOP_DATA_MOUNTPOINT:-.data/loop}:/home/loop/.loop
  faraday:
    image: r0shii/faraday:dev
    init: true
    pull_policy: always
    build:
      pull: true
      args:
        SERVICE: faraday
        VERSION_TAG: v0.2.8-alpha
      context: lnlabs
      dockerfile: deamon.Dockerfile
    container_name: faraday
    depends_on:
      lnd:
        condition: service_healthy
    networks:
      - private
    volumes:
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/faraday/.lnd:ro
      - ${FARADAY_DATA_MOUNTPOINT:-.data/faraday}:/home/faraday/.faraday
  lit:
    image: r0shii/lit:dev
    init: true
    pull_policy: always
    build:
      pull: true
      args:
        VERSION: v0.8.0-alpha
      context: lnlabs
      dockerfile: terminal.Dockerfile
    container_name: lit
    depends_on:
      lnd:
        condition: service_healthy
    networks:
      - private
    volumes:
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/lit/.lnd:ro
      - ${FARADAY_DATA_MOUNTPOINT:-.data/faraday}:/home/lit/.faraday:ro
      - ${LOOP_DATA_MOUNTPOINT:-.data/loop}:/home/lit/.loop:ro
      - ${POOL_DATA_MOUNTPOINT:-.data/pool}:/home/farlitaday/.pool:ro
      - ${LIT_DATA_MOUNTPOINT:-.data/lit}:/home/lit/.lit


networks:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.1.0/24

volumes:
  tor:
  bitcoin:

configs:
  torrc:
    file: ./configs/torrc
  bitcoin:
    file: ./configs/bitcoin.conf
  lnd:
    file: ./configs/lnd.conf
  jm:
    file: ./configs/joinmarket.cfg