version: "3.8"

x-defaults: &defaults
  init: true
  pull_policy: always
  networks:
    - private
  restart: unless-stopped    

x-build-defaults: &build-defaults
  context: ./build-context
  pull: true

x-lnd-service-defaults: &lnd-service-defaults
  <<: *defaults 
  depends_on:
    lnd:
      condition: service_healthy

services:
  tor:
    <<: *defaults
    image: r0shii/tor:dev
    build:
      <<: *build-defaults
      dockerfile: tor.Dockerfile
    configs:
      - source: torrc
        target: /etc/tor/torrc
    container_name: tor
    networks:
      private:
        ipv4_address: 10.3.1.2
    volumes:
      - tor:/var/lib/tor

  bitcoin:
    <<: *defaults
    image: r0shii/bitcoin:dev
    build:
      <<: *build-defaults
      args:
        VERSION_TAG: v23.0
      dockerfile: bitcoin.Dockerfile
    configs:
      - source: bitcoin
        target: /home/satoshi/.bitcoin/bitcoin.conf
    container_name: bitcoin
    depends_on:
      - tor
    networks:
      private:
        ipv4_address: 10.3.1.3
    volumes:
      - tor:/var/lib/tor:ro
      - bitcoin:/var/lib/bitcoin
      - ${BITCOIN_BLOCKS_MOUNTPOINT:-.data/bitcoin/.blocks}:/blocks
      - ${BITCOIN_DATA_MOUNTPOINT:-.data/bitcoin}:/home/satoshi/.bitcoin

  joinmarket:
    profiles:
    - do-not-start
    <<: *defaults
    image: r0shii/joinmarket:dev
    build:
      <<: *build-defaults
      args:
        VERSION_TAG: v0.9.8
      dockerfile: joinmarket.Dockerfile
    command: python yg-privacyenhanced.py --datadir=/srv wallet.jmdat
    configs:
      - source: jm
        target: /srv/joinmarket.cfg
    container_name: joinmarket
    depends_on:
      bitcoin:
        condition: service_healthy
    volumes:
      - tor:/var/lib/tor:ro
      - bitcoin:/var/lib/bitcoin:ro
      - ${JOINMARKET_DATA_MOUNTPOINT:-.data/joinmarket}:/srv

  lnd:
    <<: *defaults
    image: r0shii/lnd:dev
    build:
      <<: *build-defaults
      args:
        VERSION_TAG: v0.15.1-beta
      dockerfile: lnd.Dockerfile
    container_name: lnd
    configs:
      - source: lnd
        target: /home/satoshi/.lnd/lnd.conf
    depends_on:
      bitcoin:
        condition: service_healthy
    volumes:
      - tor:/var/lib/tor:ro
      - bitcoin:/var/lib/bitcoin:ro
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/satoshi/.lnd

  lndconnect:
    <<: *defaults
    image: r0shii/lndconnect:dev
    build:
      <<: *build-defaults
      dockerfile: lndconnect.Dockerfile
    container_name: lndconnect
    depends_on:
      lnd:
        condition: service_healthy
    volumes:
      - tor:/var/lib/tor:ro
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/satoshi/.lnd

  pool:
    <<: *lnd-service-defaults
    image: r0shii/pool:dev
    build:
      <<: *build-defaults
      args:
        SERVICE: pool
        VERSION_TAG: v0.5.8-alpha
      dockerfile: lnlabs-deamon.Dockerfile
    command: poold
    container_name: pool
    configs:
      - source: pool
        target: /home/satoshi/.pool/mainnet/poold.conf
        mode: 0777
    volumes:
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/satoshi/.lnd:ro
      - pool:/home/satoshi/.pool

  loop:
    <<: *lnd-service-defaults
    image: r0shii/loop:dev
    build:
      <<: *build-defaults
      args:
        SERVICE: loop
        VERSION_TAG: v0.20.1-beta
      dockerfile: lnlabs-deamon.Dockerfile
    command: loopd
    container_name: loop
    configs:
      - source: loop
        target: /home/satoshi/.loop/mainnet/loopd.conf
    volumes:
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/satoshi/.lnd:ro
      - loop:/home/satoshi/.loop
  
  faraday:
    <<: *lnd-service-defaults
    image: r0shii/faraday:dev
    build:
      <<: *build-defaults
      args:
        SERVICE: faraday
        VERSION_TAG: v0.2.8-alpha
      dockerfile: lnlabs-deamon.Dockerfile
    command: faraday --lnd.host=lnd:10009
    container_name: faraday
    volumes:
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/satoshi/.lnd:ro
      - faraday:/home/satoshi/.faraday
  
  lightning-terminal:
    <<: *lnd-service-defaults
    image: r0shii/lightning-terminal:dev
    build:
      <<: *build-defaults
      args:
        VERSION: v0.8.0-alpha
      dockerfile: lightning-terminal.Dockerfile
    container_name: lightning-terminal
    configs:
      - source: lightning-terminal
        target: /home/satoshi/.lit/lit.conf
    depends_on:
      - pool
      - loop
      - faraday
    volumes:
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/satoshi/.lnd:ro
      - faraday:/home/satoshi/.faraday:ro
      - loop:/home/satoshi/.loop:ro
      - pool:/home/satoshi/.pool:ro
      - lit:/home/satoshi/.lit

networks:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.1.0/24

volumes:
  tor:
  bitcoin:
  pool:
  loop:
  faraday:
  lit:

configs:
  torrc:
    file: ./configs/torrc
  bitcoin:
    file: ./configs/bitcoin.conf
  lnd:
    file: ./configs/lnd.conf
  jm:
    file: ./configs/joinmarket.cfg
  pool:
    file: ./configs/poold.conf
  loop:
    file: ./configs/loopd.conf
  lightning-terminal:
    file: ./configs/lit.conf