version: "3.8"

x-defaults: &defaults
  init: true
  pull_policy: always
  networks:
    - private
  restart: unless-stopped    

x-build-defaults: &build-defaults
  context: ./build-context
  pull: true

x-lnd-service-defaults: &lnd-service-defaults
  <<: *defaults 
  depends_on:
    lnd:
      condition: service_healthy

services:
  tor:
    <<: *defaults
    image: r0shii/tor:v22.11.6
    build:
      <<: *build-defaults
      dockerfile: tor.Dockerfile
    configs:
      - source: torrc
        target: /etc/tor/torrc
    container_name: tor
    networks:
      private:
        ipv4_address: 10.3.1.2
    volumes:
      - tor:/var/lib/tor

  bitcoin:
    <<: *defaults
    image: r0shii/bitcoin:v22.11.6
    build:
      <<: *build-defaults
      args:
        VERSION_TAG: v23.0
      dockerfile: bitcoin.Dockerfile
    configs:
      - source: bitcoin
        target: /home/satoshi/.bitcoin/bitcoin.conf
    container_name: bitcoin
    depends_on:
      - tor
    networks:
      private:
        ipv4_address: 10.3.1.3
    volumes:
      - tor:/var/lib/tor:ro
      - bitcoin:/var/lib/bitcoin
      - ${BITCOIN_BLOCKS_MOUNTPOINT:-.data/bitcoin/.blocks}:/blocks
      - ${BITCOIN_DATA_MOUNTPOINT:-.data/bitcoin}:/home/satoshi/.bitcoin

  joinmarket:
    <<: *defaults
    image: r0shii/joinmarket:v22.11.6
    build:
      <<: *build-defaults
      args:
        VERSION_TAG: v0.9.8
      dockerfile: joinmarket.Dockerfile
    configs:
      - source: jm
        target: /home/satoshi/.joinmarket/joinmarket.cfg
    container_name: joinmarket
    depends_on:
      bitcoin:
        condition: service_healthy
    volumes:
      - tor:/var/lib/tor:ro
      - bitcoin:/var/lib/bitcoin:ro
      - ${JOINMARKET_DATA_MOUNTPOINT:-.data/joinmarket}:/home/satoshi/.joinmarket
    secrets:
      - jm-wallet-password

  lnd:
    <<: *defaults
    image: r0shii/lnd:v22.11.6
    build:
      <<: *build-defaults
      args:
        VERSION_TAG: v0.15.4-beta
      dockerfile: lnd.Dockerfile
    container_name: lnd
    configs:
      - source: lnd
        target: /home/satoshi/.lnd/lnd.conf
    depends_on:
      bitcoin:
        condition: service_healthy
    volumes:
      - tor:/var/lib/tor:ro
      - bitcoin:/var/lib/bitcoin:ro
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/satoshi/.lnd
    secrets:
      - lnd-wallet-unlock-password

  lndconnect:
    profiles:
    - do-not-start
    <<: *lnd-service-defaults
    image: r0shii/lndconnect:v22.11.6
    build:
      <<: *build-defaults
      dockerfile: lndconnect.Dockerfile
    container_name: lndconnect
    volumes:
      - tor:/var/lib/tor:ro
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/satoshi/.lnd

  lit:
    <<: *lnd-service-defaults
    image: r0shii/lightning-terminal:v22.11.6
    build:
      <<: *build-defaults
      args:
        VERSION: v0.8.3-alpha
      dockerfile: lit.Dockerfile
    container_name: lightning-terminal
    configs:
      - source: lit
        target: /home/satoshi/.lit/lit.conf
    ports:
      - "8443:8443"
    volumes:
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/satoshi/.lnd:ro
      - faraday:/home/satoshi/.faraday
      - lit:/home/satoshi/.lit
      - loop:/home/satoshi/.loop
      - pool:/home/satoshi/.pool
    secrets:
      - lit-ui-password

  charge-lnd:
    <<: *lnd-service-defaults
    image: r0shii/charge-lnd:v22.11.6
    build:
      <<: *build-defaults
      args:
        VERSION: v0.2.12
      dockerfile: charge-lnd.Dockerfile
    container_name: charge-lnd
    configs:
      - charge-lnd
    volumes:
      - ${LND_DATA_MOUNTPOINT:-.data/lnd}:/home/satoshi/.lnd:ro

networks:
  private:
    driver: bridge
    ipam:
      config:
        - subnet: 10.3.1.0/24

volumes:
  bitcoin:
  faraday:
  lit:
  loop:
  pool:
  tor:

configs:
  torrc:
    file: ./configs/torrc
  bitcoin:
    file: ./configs/bitcoin.conf
  lnd:
    file: ./configs/lnd.conf
  jm:
    file: ./configs/joinmarket.cfg
  lit:
    file: ./configs/lit.conf
  charge-lnd:
    file: ./configs/charge-lnd.conf

secrets:
  lnd-wallet-unlock-password:
    file: ${SECRET_DATA_MOUNTPOINT:-.secrets}/lnd-wallet-unlock-password
  lit-ui-password:
    file: ${SECRET_DATA_MOUNTPOINT:-.secrets}/lit-ui-password
  jm-wallet-password:
    file: ${SECRET_DATA_MOUNTPOINT:-.secrets}/jm-wallet-password
